### ISSUE TITLE
[1.12.2] Morph causes side-effects on other players

### ISSUE THREAD

**Issue by Fatmice** [iChun/Morph#882] opened 2017-11-14 03:33 UTC
iChunUtil-1.12.2-7.0.3.jar
Morph-1.12.2-7.0.1.jar

When anyone morphs, the other player's geometries will deform in unpredictable and often hilarious ways...like growing a leg or head on their bodies.

Also, one can hear foot pad sounds around morphed players...others claim otherwise but clearly I'm not hallucinating...
![2017-11-13_21 30 52](https://user-images.githubusercontent.com/8956281/32761666-3f3ec5a0-c8ba-11e7-92ed-207d026c434e.png)
![2017-11-13_21 31 11](https://user-images.githubusercontent.com/8956281/32761667-3f529a3a-c8ba-11e7-9cf7-5505eecd0e29.png)
![2017-11-13_21 31 35](https://user-images.githubusercontent.com/8956281/32761668-3f6203d0-c8ba-11e7-8266-8cebc44ac7f9.png)
![2017-11-13_21 31 46](https://user-images.githubusercontent.com/8956281/32761669-3f772c2e-c8ba-11e7-92b1-e661f27216c0.png)

**Comment by iChun** [comment] 2017-11-14 03:59
A screenshot or better yet a video would be nice

**Comment by iChun** [comment] 2017-11-14 03:59
Oh wait nevermind. The pictures just loaded.

**Comment by iChun** [comment] 2017-11-14 12:48
Okay I think I've managed to get fix the pitter patter of morphed players, but I can't fix footstep sounds of morphed entities because there's no easy way around it (you alerted me of another bug)

Working on the malformed models now if I can replicate it.

Let me know how it goes in 7.0.2

**Comment by iChun** [comment] 2017-11-14 13:36
What other mods do you have? I can't reproduce the model issue. Can you try with just the two mods installed and get back to me how it goes?

**Comment by Fatmice** [comment] 2017-11-14 23:28
I'll take a look tonight with only Morph and report back.

**Comment by Fatmice** [comment] 2017-11-15 04:43
Okay so I'm also unable to reproduce with just a clean spongeforge server and clients with only
iChunUtil-1.12.2-7.0.3.jar
Morph-1.12.2-7.0.1.jar

My guess is it is mod interaction of some kind.  I'll have to do binary tests as I have over 100 mods.

**Comment by iChun** [comment] 2017-11-15 06:37
7.0.2 isn't released yet heh. I'm waiting for GLASS to be completed because GLASS needs an iChunUtil update.

**Comment by iChun** [comment] 2017-11-18 09:38
Any luck finding the offending mod?

**Comment by Fatmice** [comment] 2017-11-19 01:06
Okay, I've found the smallest set.
iChunUtil-1.12.2-7.0.3.jar
Morph-1.12.2-7.0.1.jar
OptiFine 1.12.2_HD_U_C6
forge-1.12.2-14.23.0.2529

**Comment by iChun** [comment] 2017-11-19 01:44
Oh. Optifine. Why am I not surprised? So the model issues don't happen
without Optifine?

**Comment by Fatmice** [comment] 2017-11-19 04:05
Yes, seems to work without issues.

**Comment by iChun** [comment] 2017-11-20 00:05
Eurgh, I don't know how I'll make it Optifine compatible... What would you suggest?

**Comment by Fatmice** [comment] 2017-11-20 11:32
What is causing the artifacts in the first place?  Optifine changes certain math functions.  This causes issues with your code changing of mesh?

**Comment by iChun** [comment] 2017-11-20 14:45
I don't know. I don't (and many other modders too) support Optifine. It's broken enough of my mods that I've basically given up with dealing with it.

As with that I'm closing this issue. Thanks for letting me know it's an Optifine bug though.

**Closed by iChun** 2017-11-20 14:45 UTC

**Comment by Fatmice** [comment] 2017-11-20 14:47
No problem. =)
