### ISSUE TITLE
Morph issue.

### ISSUE THREAD

**Issue by korcakd1** [iChun/Morph#824] opened 2016-09-24 14:35 UTC
Hello, I have some issue with Morph on ftb crackpack.
When I start the client, then it looks alright, but when I choose my world then it kicks me out.
It writes "Fatal error has occurred".
I'm sorry for my english.
Here is the log: http://pastebin.com/jAch30w8

**Comment by sudo-apt-get-install** [comment] 2016-09-24 22:08
This does not seem to be a Morph mod issue, have you tried using Morph by itself

**Comment by Tamaized** [comment] 2016-09-24 22:17
It's something between Morph and Yggdrasil from what I can tell.
"There was a critical exception handling a packet on channel Morph
java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonObject"

As for what exactly was the cause, I couldn't tell you.

**Comment by korcakd1** [comment] 2016-09-25 08:53
Morph is running by itself, but the fun is that this is official ftb pack doesn't work with it.. 
Isn't there any chance to make it work? Everything is working when i disable it, but that's not what I want.

**Comment by Tamaized** [comment] 2016-09-25 08:57
So what you're saying is Morph is working fine alone but no longer works when you enable the other mods? If this is the case you'll need to figure out which mod exactly is causing Morph to not work.

**Comment by korcakd1** [comment] 2016-09-25 09:02
Hard to tell. I have been googling mods which can cause conflict, but still no clue. Maybe I have to run trought all the mods from ftb pack? That will take some time. 
You said that there is problem with packet handling. Maybe problem with some permissions around java or something? I'm sorry for bothering you.

**Comment by Tamaized** [comment] 2016-09-25 09:04
Yes you'll have to check through the mods yourself, you can do a binary style check where you cut the mods in half, problem gone? Remove the current mods and place the other half back, split that in half and repeat. Be sure to keep ichunutil and Morph in there at all times though.

**Comment by korcakd1** [comment] 2016-09-25 09:09
I will run trought it and then let u know.

**Comment by korcakd1** [comment] 2016-09-25 09:48
So I have ran trought and there is no conflict within mods. This error is propably caused by client.

**Comment by korcakd1** [comment] 2016-09-25 10:17
I moved ftb modpack to MultiMC and everything is working just fine.

**Comment by Tamaized** [comment] 2016-09-25 14:01
So Morph didn't work alone then? That leads to my first suspicion, it's between Morph and the auth servers, something weird was going on with how you were logged in, Morph does contact the auth servers for skins and such and this is why it doesn't work along side something like mineshafter. Though I can't be completely sure as I haven't really taken a close look at Morph's code so @iChun would know best.

**Comment by korcakd1** [comment] 2016-09-25 17:55
Yes it is something like that. Morph works alone, but not with ftb client(launcher).

**Comment by iChun** [comment] 2017-11-15 06:47
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.

**Closed by iChun** 2017-11-15 06:47 UTC
