### ISSUE TITLE
Morph mod crashes the world when morphing to anything

### ISSUE THREAD

**Issue by abadigam3r** [iChun/Morph#838] opened 2017-04-04 03:05 UTC
# Hello Author **## I have a problem in morph mod and this is a photo**
 
![image](https://cloud.githubusercontent.com/assets/26889440/24640059/87ff91e6-1926-11e7-9aeb-d1b39f29d03b.png)

**Comment by Tamaized** [comment] 2017-04-04 03:08
Post logs, use pastebin or gist.
`fml-client-latest.log` would be ideal.
Be sure to post it after the error occurs, the file is written to during runtime meaning if you close and relaunch the game then the file gets wiped.

**Comment by abadigam3r** [comment] 2017-04-04 03:14
https://gist.github.com/abadigam3r/b40d873648856f0eb5b4dce1036845b3

**Comment by abadigam3r** [comment] 2017-04-04 03:23
but just for telling you i am playing SP but it says server and i didn't open lan or anything just SP 😘

**Comment by Tamaized** [comment] 2017-04-04 03:24
Stacktrace: 

> java.lang.NullPointerException
> 	at net.minecraft.client.renderer.GLAllocation.func_74523_b(SourceFile:23) ~[ban.class:?]
> 	at morph.client.model.ModelHelper.getModelCubesCopy(ModelHelper.java:48) ~[ModelHelper.class:?]
> 	at morph.client.model.ModelMorph.<init>(ModelMorph.java:46) ~[ModelMorph.class:?]
> 	at morph.client.morph.MorphInfoClient.<init>(MorphInfoClient.java:37) ~[MorphInfoClient.class:?]
> 	at morph.common.packet.PacketMorphInfo.handleClient(PacketMorphInfo.java:158) ~[PacketMorphInfo.class:?]
> 	at morph.common.packet.PacketMorphInfo.execute(PacketMorphInfo.java:100) ~[PacketMorphInfo.class:?]
> 	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:84) ~[ChannelHandler$PacketExecuter.class:?]
> 	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:66) ~[ChannelHandler$PacketExecuter.class:?]
> 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]

This is the exact same issue as #836 

From the log it also shows your iChunUtil version is 4.1.3, the latest is 4.2.3
It also shows you using Morph 0.9.0, latest is  0.9.3.

Update then report back to see if it fixes the issue.

**Comment by abadigam3r** [comment] 2017-04-04 03:26
ok i'll try 😘

**Comment by abadigam3r** [comment] 2017-04-04 03:42
same error 😭 https://gist.github.com/abadigam3r/4dd494db7950447d2e0ff92bad45dc2b

**Comment by abadigam3r** [comment] 2017-04-04 04:12
@Tamaized  anything?

**Comment by Tamaized** [comment] 2017-04-04 04:24
This isn't a live chat :P I check when I have the time to.

Anyway, same error and I really don't know the cause, i'll leave it to iChun.

**Comment by abadigam3r** [comment] 2017-04-04 04:30
ok thanks @Tamaized

**Comment by Tamaized** [comment] 2017-04-04 04:36
though based on the other issue I linked, if you have Optifine installed try removing it. I can't check atm to see if you do or not.

**Comment by iChun** [comment] 2017-04-04 04:45
It is installed. FYI any mod at and still at 1.7.10, all support has been
dropped for them to favour progressing forwards.

On 4 Apr 2017 12:36 pm, "Tamaized" <notifications@github.com> wrote:

though based on the other issue I linked, if you have Optifine installed
try removing it. I can't check atm to see if you do or not.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/iChun/Morph/issues/838#issuecomment-291391247>, or mute
the thread

**Comment by abadigam3r** [comment] 2017-04-04 04:48
> yeah thanks i removed  optifine and it worked

 ,but **is there any way that i can install optifine?**

**Comment by 0-0oyoguys** [comment] 2017-09-16 22:22
I have the same problem, but its when i load a world. Any help? Im using iChunUtil 4.2.2 and Morph 0.9.2 (i have 1.7.10 forge.)

**Comment by 0-0oyoguys** [comment] 2017-09-16 22:23
[16:57:00] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[16:57:00] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[16:57:00] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[16:57:00] [main/INFO] [FML]: Forge Mod Loader version 7.99.36.1558 for Minecraft 1.7.10 loading
[16:57:00] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.6.8, installed at /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
[16:57:00] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:57:00] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[16:57:00] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:57:00] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:57:00] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:57:03] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[16:57:03] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[16:57:03] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:57:03] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[16:57:06] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[16:57:06] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[16:57:06] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[16:57:10] [main/INFO]: Setting user: RedAssassin
[16:57:12] [Client thread/INFO]: LWJGL Version: 2.9.1
[16:57:13] [Client thread/INFO] [STDOUT]: [tv.twitch.StandardCoreAPI:<init>:16]: If on Windows, make sure to provide all of the necessary dll's as specified in the twitchsdk README. Also, make sure to set the PATH environment variable to point to the directory containing the dll's.
[16:57:13] [Client thread/ERROR]: Couldn't initialize twitch stream
[16:57:15] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[16:57:15] [Client thread/INFO] [FML]: MinecraftForge v10.13.4.1558 Initialized
[16:57:15] [Client thread/INFO] [FML]: Replaced 183 ore recipies
[16:57:15] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[16:57:15] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[16:57:15] [Client thread/INFO] [FML]: Searching /Users/noah/Library/Application Support/minecraft/mods for mods
[16:57:26] [Client thread/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[16:57:26] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, iChunUtil, Morph] at CLIENT
[16:57:26] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, iChunUtil, Morph] at SERVER
[16:57:27] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:Morph, Improved Cow and Chicken Models, Sky:Water Demo Pack, Vaders Stacked Items Pack V1.1 For MC 1.11.zip, Smooth Transitions
[16:57:27] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[16:57:27] [Client thread/INFO] [FML]: Found 341 ObjectHolder annotations
[16:57:27] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[16:57:27] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[16:57:27] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[16:57:27] [iChunUtil Patron Getter Thread/INFO] [STDOUT]: [info.mineshafter.hacks.InterceptHttpsHandler:openConnection:38]: Should handle? https://raw.github.com/iChun/iChunUtil/master/src/main/resources/assets/ichunutil/mod/patrons.json false
[16:57:28] [Client thread/INFO] [FML]: Applying holder lookups
[16:57:28] [Client thread/INFO] [FML]: Holder lookups applied
[16:57:28] [Client thread/INFO] [FML]: Injecting itemstacks
[16:57:28] [Client thread/INFO] [FML]: Itemstack injection complete
[16:57:28] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[16:57:28] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[16:57:29] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[16:57:29] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[16:57:30] [Thread-12/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[16:57:30] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[16:57:30] [Sound Library Loader/INFO]: Sound engine started
[16:57:30] [Client thread/INFO]: Created: 16x16 textures/blocks-atlas
[16:57:30] [Client thread/INFO]: Created: 16x16 textures/items-atlas
[16:57:30] [iChunUtil Mod Version Check/INFO] [STDOUT]: [info.mineshafter.hacks.InterceptHttpsHandler:openConnection:38]: Should handle? https://raw.github.com/iChun/iChunUtil/master/src/main/resources/assets/ichunutil/mod/versions.json false
[16:57:30] [Client thread/INFO] [FML]: Injecting itemstacks
[16:57:30] [Client thread/INFO] [FML]: Itemstack injection complete
[16:57:30] [Client thread/INFO] [iChunUtil]: [4.2.2] Opting out of stat collection :(
[16:57:30] [Morph Online Resource Thread/INFO] [STDOUT]: [info.mineshafter.hacks.InterceptHttpsHandler:openConnection:38]: Should handle? https://raw.github.com/iChun/Morph/legacy1710/src/main/resources/assets/morph/mod/AbilitySupport.json false
[16:57:30] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 5 mods
[16:57:30] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:Morph, Improved Cow and Chicken Models, Sky:Water Demo Pack, Vaders Stacked Items Pack V1.1 For MC 1.11.zip, Smooth Transitions
[16:57:31] [Morph Online Resource Thread/INFO] [Morph]: [0.9.2] Found and mapped ability mappings for 24 presumably Minecraft mobs.
[16:57:31] [Morph Online Resource Thread/INFO] [STDOUT]: [info.mineshafter.hacks.InterceptHttpsHandler:openConnection:38]: Should handle? https://raw.github.com/iChun/Morph/legacy1710/src/main/resources/assets/morph/mod/NBTStripper.json false
[16:57:31] [Client thread/INFO]: Created: 256x256 textures/items-atlas
[16:57:32] [Client thread/INFO]: Created: 512x256 textures/blocks-atlas
[16:57:32] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[16:57:32] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[16:57:32] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[16:57:32] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[16:57:32] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[16:57:32] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[16:57:33] [Thread-16/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[16:57:33] [Thread-16/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[16:57:33] [Thread-16/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[16:57:33] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[16:57:33] [Sound Library Loader/INFO]: Sound engine started
[16:57:33] [Client thread/ERROR]: ########## GL ERROR ##########
[16:57:33] [Client thread/ERROR]: @ Post startup
[16:57:33] [Client thread/ERROR]: 1281: Invalid value
[16:57:56] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[16:57:56] [Server thread/INFO]: Generating keypair
[16:57:56] [Server thread/INFO]: Converting map!
[16:57:56] [Server thread/INFO]: Scanning folders...
[16:57:56] [Server thread/INFO]: Total conversion count is 0
[16:57:56] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[16:57:56] [Server thread/INFO] [FML]: Applying holder lookups
[16:57:56] [Server thread/INFO] [FML]: Holder lookups applied
[16:57:58] [Server thread/INFO] [FML]: Loading dimension 0 (Morph???) (net.minecraft.server.integrated.IntegratedServer@5d51981a)
[16:57:58] [Server thread/INFO] [FML]: Loading dimension 1 (Morph???) (net.minecraft.server.integrated.IntegratedServer@5d51981a)
[16:57:58] [Server thread/INFO] [FML]: Loading dimension -1 (Morph???) (net.minecraft.server.integrated.IntegratedServer@5d51981a)
[16:57:58] [Server thread/INFO]: Preparing start region for level 0
[16:57:59] [Client thread/INFO] [STDOUT]: [info.mineshafter.hacks.InterceptHttpsHandler:openConnection:38]: Should handle? https://sessionserver.mojang.com/blockedservers true
[16:57:59] [Server thread/INFO]: Changing view distance to 5, from 10
[16:57:59] [Netty Client IO #0/INFO] [FML]: Server protocol version 2
[16:57:59] [Netty IO #1/INFO] [FML]: Client protocol version 2
[16:57:59] [Netty IO #1/INFO] [FML]: Client attempting to join with 5 mods : mcp@9.05,FML@7.10.99.99,iChunUtil@4.2.2,Forge@10.13.4.1558,Morph@0.9.2
[16:57:59] [Netty IO #1/INFO] [FML]: Attempting connection with missing mods [] at CLIENT
[16:57:59] [Netty Client IO #0/INFO] [FML]: Attempting connection with missing mods [] at SERVER
[16:57:59] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[16:57:59] [Server thread/INFO]: RedAssassin[local:E:8c75ee75] logged in with entity id 15 at (314.5, 4.0, 187.5)
[16:57:59] [Server thread/INFO]: RedAssassin joined the game
[16:57:59] [Client thread/INFO] [FML]: [Client thread] Client side modded connection established
[16:58:00] [pool-2-thread-1/INFO] [STDOUT]: [info.mineshafter.hacks.InterceptHttpsHandler:openConnection:38]: Should handle? https://sessionserver.mojang.com/session/minecraft/profile/aa3ba683a15619cac9266d4e81183c37?unsigned=true true
[16:58:00] [Client thread/INFO] [STDOUT]: [info.mineshafter.hacks.InterceptHttpsHandler:openConnection:38]: Should handle? https://api.mojang.com/profiles/minecraft true
[16:58:00] [pool-2-thread-1/INFO] [STDOUT]: [info.mineshafter.intercept.ProfileHandler:getProfile:73]: ProfileHandler.getProfile(aa3ba683a15619cac9266d4e81183c37)
[16:58:00] [pool-2-thread-1/INFO] [STDOUT]: [info.mineshafter.datasources.MineshafterProfileAuthority:getProfile:36]: MineshafterProfileClient.getProfile(aa3ba683a15619cac9266d4e81183c37)
[16:58:00] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel Morph
java.lang.NullPointerException
	at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:53) ~[YggdrasilGameProfileRepository.class:?]
	at ichun.common.core.EntityHelperBase.getPartialGameProfileFromName(EntityHelperBase.java:151) ~[EntityHelperBase.class:?]
	at ichun.common.core.EntityHelperBase.getFullGameProfileFromName(EntityHelperBase.java:101) ~[EntityHelperBase.class:?]
	at morph.common.morph.MorphState.createPlayer(MorphState.java:173) ~[MorphState.class:?]
	at morph.common.morph.MorphState.readTag(MorphState.java:123) ~[MorphState.class:?]
	at morph.common.packet.PacketMorphStates.handleClient(PacketMorphStates.java:83) ~[PacketMorphStates.class:?]
	at morph.common.packet.PacketMorphStates.execute(PacketMorphStates.java:62) ~[PacketMorphStates.class:?]
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:84) ~[ChannelHandler$PacketExecuter.class:?]
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:66) ~[ChannelHandler$PacketExecuter.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.6.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[?:1.6.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[?:1.6.0_65]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[?:1.6.0_65]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.6.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[?:1.6.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[?:1.6.0_65]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[?:1.6.0_65]
	at info.mineshafter.GameStarter.main(GameStarter.java:24) [ms-starter.jar:?]
[16:58:00] [Server thread/INFO]: RedAssassin lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[16:58:00] [Server thread/INFO]: RedAssassin left the game
[16:58:00] [Server thread/INFO]: Stopping singleplayer server as player logged out
[16:58:00] [Server thread/INFO]: Stopping server
[16:58:00] [Server thread/INFO]: Saving players
[16:58:00] [Server thread/INFO]: Saving worlds
[16:58:00] [Server thread/INFO]: Saving chunks for level 'Morph???'/Overworld
[16:58:00] [pool-2-thread-1/INFO] [STDOUT]: [info.mineshafter.datasources.MineshafterProfileAuthority:getProfile:47]: MS.getProfile: <html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>

[16:58:00] [Server thread/INFO]: Saving chunks for level 'Morph???'/Nether
[16:58:00] [Server thread/INFO]: Saving chunks for level 'Morph???'/The End
[16:58:02] [Server thread/INFO] [FML]: Unloading dimension 0
[16:58:02] [Server thread/INFO] [FML]: Unloading dimension -1
[16:58:02] [Server thread/INFO] [FML]: Unloading dimension 1
[16:58:02] [Server thread/INFO] [FML]: Applying holder lookups
[16:58:02] [Server thread/INFO] [FML]: Holder lookups applied
[16:58:05] [Netty Client IO #0/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, iChunUtil, Morph] at SERVER (i didnt crash, it just kicked me from the world. this is the console.)

**Comment by Tamaized** [comment] 2017-09-17 04:02
^ mineshafter isnt compatible with morph.

**Comment by iChun** [comment] 2017-11-15 06:45
hahahha oh right the mineshafter crash.

Anyways: This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.

**Closed by iChun** 2017-11-15 06:45 UTC

**Comment by HunterTubeGaming** [comment] 2022-04-23 00:19
hey i have a problem when i open the menu with the [ ] keybinds it crashes i have no clue why can some please help me?
and this world is too important thanks goodness im my favorite mob the creeper and hes not big like the mutants but please i need help soon i want to become stuff like dragons

**Comment by abadigam3r** [comment] 2022-04-23 01:20
Oh god, it's been 5 Years.
I didn't even know I have github acc

**Comment by abadigam3r** [comment] 2022-04-23 01:21
> hey i have a problem when i open the menu with the [ ] keybinds it crashes i have no clue why can some please help me? and this world is too important thanks goodness im my favorite mob the creeper and hes not big like the mutants but please i need help soon i want to become stuff like dragons

just open a new issue
this issue is 5 years old.

**Comment by HunterTubeGaming** [comment] 2022-04-23 02:23
> > hey i have a problem when i open the menu with the [ ] keybinds it crashes i have no clue why can some please help me? and this world is too important thanks goodness im my favorite mob the creeper and hes not big like the mutants but please i need help soon i want to become stuff like dragons
> 
> just open a new issue this issue is 5 years old.

wdym open a issue?

**Comment by abadigam3r** [comment] 2022-04-23 02:25
> > > hey i have a problem when i open the menu with the [ ] keybinds it crashes i have no clue why can some please help me? and this world is too important thanks goodness im my favorite mob the creeper and hes not big like the mutants but please i need help soon i want to become stuff like dragons
> > 
> > 
> > just open a new issue this issue is 5 years old.
> 
> wdym open a issue?

you already did
this is your issue #1202

**Comment by HunterTubeGaming** [comment] 2022-04-23 02:26
> > > > hey i have a problem when i open the menu with the [ ] keybinds it crashes i have no clue why can some please help me? and this world is too important thanks goodness im my favorite mob the creeper and hes not big like the mutants but please i need help soon i want to become stuff like dragons
> > > 
> > > 
> > > just open a new issue this issue is 5 years old.
> > 
> > 
> > wdym open a issue?
> 
> you already did this is your issue #1202

oh ok

**Comment by iChun** [comment] 2022-04-23 02:30
Locking: This is an old & closed issue from 5 years ago. You've made your own issue, all correspondence regarding your issue will happen there.
