### ISSUE TITLE
Unintended Movment on four-legged creatures (MC 1.7.10)(iChunUtil 4.2.2)(Morph-Beta 4.2.2)

### ISSUE THREAD

**Issue by TheJster442** [iChun/Morph#808] opened 2016-03-12 03:34 UTC
When I morph into a four-legged creature, my player keeps sliding to Northwest and will NoClip through blocks and I will suffocate in the blocks. Is there a fix? I have updated to the latest version of iChunUtil, for 1.7.10, to work with morph, and I have Morph-Beta 0.9.2, and iChunUtil, ver. 4.2.2.

**Comment by HyperMan19680** [comment] 2016-10-15 05:23
I can confirm this bug, I keep sliding sometines too when I morph. And it just gets faster and faster.

**Comment by iChun** [comment] 2017-11-15 06:53
This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.

**Closed by iChun** 2017-11-15 06:53 UTC
