### ISSUE TITLE
"Unexpected Error"

### ISSUE THREAD

**Issue by CommYutzy** [iChun/Morph#937] opened 2018-02-28 04:15 UTC
Same error has happened three times between two members on my server. Two of the incidents were immediately following them killing an aggressive mob (zombie/skelly). The last one was when the member was killed by a mob. Identical crash logs in all scenarios.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.4-1.12.2-anarchy.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.6.8.jar)
  CorePlugin (ForgeEndertech-1.12.1-4.3.1.0-build.0071.jar)
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.12.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.144.jar)
  LoadingPlugin (AdChimneys-1.12.1-3.2.1.2-build.0079.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-78-core.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  BCModPlugin (backpacks+1.12.2+-+3.4.3.jar)
  ModFixLC (ModFix-1.12.2-1.0.0.1.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  TransformerLoader (OpenComputers-MC1.12.1-1.7.1.43.jar)
  LoadingPlugin (Quark-r1.4-122.jar)
  MDECore-Core (mdecore-1.12-1.0.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 2/27/18 10:25 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at me.ichun.mods.morph.client.core.EventHandlerClient.onClientTick(EventHandlerClient.java:836)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1656_EventHandlerClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:348)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1909)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.ichun.mods.morph.client.core.EventHandlerClient.onClientTick(EventHandlerClient.java:836)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1656_EventHandlerClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:348)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['[redacted]'/7330, l='MpServer', x=157.50, y=73.00, z=-19.50]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (160,64,-16), Chunk: (at 0,4,0 in 10,-1; contains blocks 160,0,-16 to 175,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 113445 game time, 124255 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	
[Removed entities for brevity]

	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by CDAGaming** [comment] 2018-02-28 18:16
Which Forge Version are you using. For me, it crashes on load

**Comment by CommYutzy** [comment] 2018-03-01 03:17
Forge 2620

**Comment by CDAGaming** [comment] 2018-03-01 03:40
Forge 2623:

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from iChunUtil (ichunutil)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:227)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:500)

I'll see if i can fork this repo and find a fix

**Comment by iChun** [comment] 2019-03-02 00:59
This should be fixed on 7.1.3 when it's released.

**Closed by iChun** 2019-03-02 00:59 UTC
