### ISSUE TITLE
STOPED WORKING

### ISSUE THREAD

**Issue by epicrush** [iChun/Morph#807] opened 2016-03-09 20:24 UTC
after about half an hour, the whole thing just stopped working commands, absorbing mobs and general morphing where I already had one restarting game doesn't work I tried getting ichun until and the mod again but no luck!

**Comment by Tamaized** [comment] 2016-03-09 22:12
And you're positive the mod is even loaded?

**Comment by epicrush** [comment] 2016-03-10 07:33
Yes I'm sure, I can press the [ and ] keys and my character comes up in the
top corner and I have the morph commands

**Comment by iChun** [comment] 2016-03-10 12:11
But it stops working. Have you tried like, I don't know, morphing to
another mob?

**Comment by epicrush** [comment] 2016-03-10 17:10
I can't even get another mob! It WON'T absorb the mob

**Comment by Tamaized** [comment] 2016-03-10 17:27
What version of Morph and MinecraftForge? Also if you have any mods installed is it possible it could be a mod conflict? Though I highly doubt that with this kind of issue.

**Comment by simfrek** [comment] 2016-06-12 21:55
hi, i am also having the same problem, i can open the menu, but i cannot obtain any new morphs, it worked before but now it will not let me gain new morphs, i even tried deleting my player data but no luck

**Comment by Tamaized** [comment] 2016-06-12 22:12
@simfrek have you checked the config for anything that may prevent you from getting morphs? It could also be a mod conflict. Also make sure you're opening the right GUI and such.

**Comment by Tamaized** [comment] 2016-06-13 00:28
Best thing to do would be to figure out if it's a mod conflict, if so figure out which mod is the cause and report it to that mod author.
If it's an issue with morph alone for some strange reason, you can yell at @iChun :D

**Comment by simfrek** [comment] 2016-06-13 00:43
everyone else on my server can use morph fine its just me that cannot use it anymore, we didnt add anything, just suddenly it wouldnt absorb any more morphs

**Comment by Tamaized** [comment] 2016-06-13 00:53
The only thing that I can think of is the configs, you checked the one on the server right? Nothing else really comes to mind since you said you've wiped your player data so I doubt it had anything to do with the amount of morphs or what morphs you had.

**Comment by simfrek** [comment] 2016-06-13 01:25
yes weve tried deleting the configs on the server
and its only effecting one player out of 6

**Comment by simfrek** [comment] 2016-06-13 14:04
can you think of any ways to try to at least temp fix it so that person can use morph?

**Comment by Tamaized** [comment] 2016-06-13 15:10
I'm out of ideas sadly, and I think iChun is too busy right now to help.

**Comment by simfrek** [comment] 2016-06-13 16:07
ok, ill keep subscribed incase he does get any time

**Comment by iChun** [comment] 2016-06-13 16:27
Does it work for you if you try it in a single player world? OH. UHM. I just thought of this, did you change your player name, at all, at any point?

**Comment by simfrek** [comment] 2016-06-13 19:54
no, my player name has always been the same

**Comment by simfrek** [comment] 2016-06-13 20:52
it works in single player yes, its just that world it doesnt work in, it used to work then suddenly stopped

**Comment by epicrush** [comment] 2016-06-13 21:04
Not sure but I have been trying to get Microsoft to restore my account for
months now and I will let you know if it does anything.
On 13 Jun 2016 15:05, "Corey Chilton" <notifications@github.com> wrote:

can you think of any ways to try to at least temp fix it so that person can
use morph?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/iChun/Morph/issues/807#issuecomment-225590590>, or mute
the thread
<https://github.com/notifications/unsubscribe/AQ7cXCKBi2PxQ3K8JGn934VgrmLjN_g6ks5qLWOKgaJpZM4HtHQo>
.

**Comment by Tamaized** [comment] 2016-06-13 21:05
I feel like another mod is involved with the issue, like say maybe something done with a specific mod on the server caused some thing fishy to happen between it and morph, what that mod is and why I couldn't tell you. Perhaps instead of the mod saving its nbt data (if it used any) to the player file it stored it somewhere else which could explain why deleting the player file didnt work.

**Comment by epicrush** [comment] 2016-06-13 21:12
It might have something to do with it being compatible with mods, it could
be certain morphs that do it on mine, it started after I got morphs from
the Orespawn mod and the only other mod installed was flans mod

**Comment by iChun** [comment] 2016-06-17 05:56
Do you happen to have Chance Cubes? Also woah how has it been 3 days already?!

**Comment by simfrek** [comment] 2016-06-17 13:58
no, im using the direwolf20 modpack with a couple changes, we added hardcore ender expansion, and draconic evolution, we also removed a few of the less needed mods such as bibliocraft

**Comment by simfrek** [comment] 2016-06-17 16:30
i managed to fix it by re making all server files and copying the world over

**Comment by Tamaized** [comment] 2016-06-17 20:06
Would be nice if we figured out the exact issue though so it could possibly be fixed in the future.

**Comment by simfrek** [comment] 2016-06-21 23:48
from what i could gather before the other files were deleted it must have been somewhere in the server files that was not in the world folder as replacing the other files seemed to fix it. probably in the libraries folder, the config folder or the scripts folder perhaps

**Comment by Tamaized** [comment] 2016-06-22 00:32
Wouldn't be the libraries as just stuff Minecraft loads to run, such as LWJGL. Anyway it would go back to being done mod saving their player not data for whatever outside the player file which is probably some boolean saying hey I'm active, run code. Which broke Morph. Sadly we may not know which mod :/

**Comment by epicrush** [comment] 2016-07-11 15:25
Sorry i havent been responding in a while, i have had some email problems. My computer broke and I had to reset it but I have downloaded the mod again I will see if it works well and if another system program was blocking it but my wifi is horrible recently so it may take a while to download forge and minecraft again, I will tell you if it works. 


Sent from my Samsung device

-------- Original message --------

**Closed** 2017-11-15 06:54 UTC
