### ISSUE TITLE
Player takes damage when morphed into a chicken or baby chicken and jumping within a one-block-tall space

### ISSUE THREAD

**Issue by Nevrai** [iChun/Morph#1220] opened 2022-09-13 15:45 UTC
When you’re morphed into a mob smaller than a player (e.g., a chicken or baby chicken), you take damage whenever you’re in a one-block-tall space and jump, which is quite frustrating as it makes it difficult to use Morph when mining or doing cable management. If you die, the death message is the suffocation message.

Seems similar to #560, but that was an issue caused by Tinkers’ Construct that was fixed eight years ago, so I assume it’s unrelated (installed Tinkers’ version is the latest for 1.12.2, 2.13.0.183).

If this is not going to be fixed, does anyone at least know if there’s a workaround to this? E.g., a mob 0.5 blocks tall or smaller that isn’t affected by this bug?

**Edit:** I tried replicating the issue morphed as a bat, and thankfully, it didn’t occur, so assuming this won’t be fixed due to it being 1.12.2, that is at least a workaround. If you want to access 1-block-tall spaces, morph into a bat,.

### Versions
* **Minecraft:** 1.12.2
* **Morph:** 7.2.1
* **iChunUtil:** 7.2.2
* **Forge:** 14.23.5.2860

**Comment by iChun** [comment] 2022-09-13 18:31
If I remember right it's cause this mob's eye height is too high up in the entity bounding box that if you jump, Minecraft's calculations thinks you're in a block and then you get suffocation. 

The way Minecraft calculates this changed in later versions so the 1.16 version isn't affected by this.

As you've figured, MC 1.12.2 is no longer supported so I'm afraid I'm going to be closing this issue. As it's caused by vanilla behaviour, there's not much I can really recommend (and I don't know if I'd even remember any workaround, really, it's been way too long).

**Closed as completed by iChun** 2022-09-13 18:31 UTC
