### ISSUE TITLE
Forcing morph is not working if player own this morph.

### ISSUE THREAD

**Issue by Cestis** [iChun/Morph#596] opened 2014-08-22 22:50 UTC
For example: /morph morphtarget player true
doesnt work if player transformed into his target before

same with method morphPlayer with "forced" = true, this method is just returning false at some point if you own morph's entity given in "living" argument.
please fix as soon as you can, thanks

**Comment by iChun** [comment] 2017-11-16 01:32
The Morph command has been revamped. /morph morph should now work as intended and there is a new /morph give  to actually give the player the morph.

This issue is being closed as a purge of issues due to the Morph rewrite to 1.12.2 finally being released. Support for the 1.7.10 version has long been dropped and focus has shifted to the 1.12.2 version of the mod instead.

**Closed by iChun** 2017-11-16 01:32 UTC
